const V=(()=>{const q=new URLSearchParams(location.search).get('v'),b=document.body.dataset.v;let v=b&&b!=='auto'?b:(q||(()=>{try{return localStorage.getItem('kf_v')}catch(e){}})()||'corp');if(v!=='mod')v='corp';try{localStorage.setItem('kf_v',v)}catch(e){}document.body.classList.add('v-'+v);return v})();
const HOME=V==='mod'?'moderne.html':'index.html';
const LOGO=c=>'<svg class="lg" viewBox="0 0 200 200" style="color:'+c+'" aria-label="KIMFIX"><path d="M20 78 100 18l80 60" fill="none" stroke="currentColor" stroke-width="13"/><circle cx="100" cy="58" r="10" fill="none" stroke="#f5c400" stroke-width="7"/><text x="100" y="122" text-anchor="middle" font-family="AB,Arial Black,sans-serif" font-size="54" fill="currentColor">KIM</text><text x="100" y="172" text-anchor="middle" font-family="AB,Arial Black,sans-serif" font-size="54" fill="currentColor">FIX</text><rect x="52" y="182" width="32" height="7" fill="#1f8a3b"/><rect x="84" y="182" width="32" height="7" fill="#d21f26"/><rect x="116" y="182" width="32" height="7" fill="currentColor"/></svg>';
(function(){
 const here=location.pathname.split('/').pop()||'index.html';
 const nav=[[HOME,'Accueil',''],['produits.html','Gamme','<span class="pst y">5</span>'],[HOME+'#calcul','Calculateur','<span class="pst r">outil</span>'],['revendeurs.html','Revendeurs','<span class="pst k">pro</span>'],[HOME+'#contact','Contact','']];
 const act=h=>h.split('#')[0]===here&&!h.includes('#')?' class="act"':'';
 document.getElementById('hdr').innerHTML='<header class="top" id="top-h"><a class="logo" href="'+HOME+'">'+LOGO('#fff')+'<span>KIMFIX</span></a><nav>'+nav.map(n=>'<a href="'+n[0]+'"'+act(n[0])+'>'+n[1]+n[2]+'</a>').join('')+'</nav><div class="hr"><a class="cta" href="revendeurs.html">Devenir revendeur</a><button class="burger" type="button" aria-label="Menu">☰</button></div></header><div class="menu" id="menu"><button class="mx" type="button" aria-label="Fermer">✕</button>'+nav.map(n=>'<a href="'+n[0]+'">'+n[1]+n[2]+'</a>').join('')+'</div>';
 const other=V==='mod'?'corp':'mod',u=new URL(location.href);u.searchParams.set('v',other);u.hash='';
 let t=u.pathname.split('/').pop()||'index.html';if(t==='index.html'||t==='moderne.html')t=other==='mod'?'moderne.html':'index.html';
 const sw=document.createElement('a');sw.className='vswitch';sw.href=t+u.search;sw.innerHTML=V==='mod'?'<span class="vs-i">🏢</span><span><small>Passer en</small>Version corporate</span>':'<span class="vs-i">⚡</span><span><small>Découvrir la</small>Version chantier</span>';document.body.appendChild(sw);
 const f=document.getElementById('ftr');if(f)f.innerHTML='<footer class="ft"><div class="wrap fg"><div>'+LOGO('#fff')+'<p>Mousse polyuréthane fabriquée en Algérie. Qualité · Performance · Innovation.</p><p class="ar">ينفع و يمتع</p></div><div><h4>Gamme</h4>'+ORDER.map(k=>'<a href="produit.html?p='+k+'">'+P[k].name+(P[k].vol?' · '+P[k].vol+'L':'')+'</a>').join('')+'</div><div><h4>Professionnels</h4><a href="revendeurs.html">Devenir revendeur</a><a href="'+HOME+'#calcul">Calculateur de mousse</a><a href="'+HOME+'#contact">Nous écrire</a></div><div><h4>Suivez-nous</h4><a href="'+FB+'" target="_blank" rel="noopener">Facebook · KimFix</a><a href="'+IG+'" target="_blank" rel="noopener">Instagram · kimfix.moussepu</a></div></div><div class="wrap fb"><span>© KIMFIX · Made in Bladi 🇩🇿</span><span>Maquette réalisée par Webminds</span></div></footer>';
 const b=document.createElement('div');b.id='wm-demo';b.textContent='Maquette de démonstration réalisée par Webminds · Proposition non officielle, aucun formulaire n\'est enregistré';document.body.appendChild(b);
 const m=document.getElementById('menu');document.addEventListener('click',e=>{if(e.target.closest('.burger'))m.classList.add('open');if(e.target.closest('.mx')||e.target.closest('.menu a'))m.classList.remove('open')});
 const th=document.getElementById('top-h');const s=()=>th.classList.toggle('solid',scrollY>30);addEventListener('scroll',s,{passive:true});s();
 const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in');io.unobserve(x.target)}}),{threshold:.08});
 window.reveal=()=>document.querySelectorAll('.rv:not([data-o])').forEach(e=>{e.dataset.o=1;io.observe(e)});reveal();
})();
function okForm(f,msg){const b=f.querySelector('button[type=submit]'),t=b.textContent;b.textContent=msg;b.disabled=true;b.classList.add('done');setTimeout(()=>{f.reset();b.textContent=t;b.disabled=false;b.classList.remove('done')},3200)}
const WILAYAS='Adrar,Chlef,Laghouat,Oum El Bouaghi,Batna,Béjaïa,Biskra,Béchar,Blida,Bouira,Tamanrasset,Tébessa,Tlemcen,Tiaret,Tizi Ouzou,Alger,Djelfa,Jijel,Sétif,Saïda,Skikda,Sidi Bel Abbès,Annaba,Guelma,Constantine,Médéa,Mostaganem,M\'Sila,Mascara,Ouargla,Oran,El Bayadh,Illizi,Bordj Bou Arréridj,Boumerdès,El Tarf,Tindouf,Tissemsilt,El Oued,Khenchela,Souk Ahras,Tipaza,Mila,Aïn Defla,Naâma,Aïn Témouchent,Ghardaïa,Relizane,Timimoun,Bordj Badji Mokhtar,Ouled Djellal,Béni Abbès,In Salah,In Guezzam,Touggourt,Djanet,El M\'Ghair,El Meniaa'.split(',');
function calcInit(root){
 const q=s=>root.querySelector(s);const run=()=>{const L=+q('#cl').value||0,w=+q('#cw2').value||0,d=+q('#cd').value||0;const vol=L*100*w*d/1000;q('#cv').textContent=vol.toFixed(1).replace('.',',')+' L';
  q('#cres').innerHTML=['c22','c32','c52','c72'].map(k=>{const n=vol>0?Math.ceil(vol/P[k].vol):0;return '<div class="cr"><img src="'+P[k].img+'" alt=""><b>'+n+'</b><span>× '+P[k].vol+'L</span></div>'}).join('')};
 root.querySelectorAll('input').forEach(i=>i.addEventListener('input',run));run()}
